# Generated by Django 4.1.7 on 2023-02-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Jismoniy shaxs', 'Jismoniy'), ('Yuridik shaxs', 'Yuridik')], default='Yuridik shaxs', max_length=255)),
                ('fish', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=9)),
                ('summa', models.IntegerField()),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
