# Generated by Django 4.1.7 on 2023-02-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Moderatsiyada', 'Moderatsiyada'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor qilingan', 'Bekor Qilingan')], default='Yangi', max_length=15),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='type',
            field=models.CharField(choices=[('Jismoniy shaxs', 'Jismoniy'), ('Yuridik shaxs', 'Yuridik')], default='Yuridik shaxs', max_length=15),
        ),
    ]
