# Generated by Django 4.1.7 on 2023-02-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sponsors_status_alter_sponsors_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsors',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AddField(
            model_name='sponsors',
            name='payment',
            field=models.CharField(choices=[('Naqd', 'Naqd'), ("Pul o'tkazmalari", 'Pul Otkazmalari')], default='Naqd', max_length=16),
        ),
    ]
