# Generated by Django 4.1.7 on 2023-02-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sponsors_options_sponsors_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTMs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'OTM',
                'verbose_name_plural': 'OTMs',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr')], default='Bakalavr', max_length=15)),
                ('fish', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=9)),
                ('contract', models.IntegerField()),
                ('otm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.otms')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
